### ISSUE TITLE
Loading LLAMA Error 

### ISSUE THREAD

**Issue by zerocore2340** [Vision-CAIR/MiniGPT-4#14]
Might be dumb question , but any ideas what this error means ? / solve it ?

`Loading LLAMA
Traceback (most recent call last):
  File "/content/drive/MyDrive/chatgpt4/MiniGPT-4/demo.py", line 57, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
  File "/content/drive/MyDrive/chatgpt4/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 241, in from_config
    model = cls(
  File "/content/drive/MyDrive/chatgpt4/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 85, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/usr/local/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/envs/minigpt4/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/usr/local/envs/minigpt4/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/envs/minigpt4/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `

**Comment by jacky539027** [comment]
I encountered the same problem, how was it resolved?

**Comment by jacky539027** [comment]
@zerocore2340 I encountered the same problem, how was it resolved?

**Comment by xxp912** [comment]
You should install "git LFS" first, and the use the command to download:
'''
git lfs install
git clone https://huggingface.co/lmsys/vicuna-13b-delta-v0
'''
This is the true bag to download: 
https://huggingface.co/lmsys/vicuna-13b-delta-v0/tree/main
you can compare the file size of vicuna-13b-delta-v0 you have download with the website.
