### ISSUE TITLE
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wuhongsheng** [Vision-CAIR/MiniGPT-4#141]
I try conda env create -f environment.yml  get  this error info :
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 152, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 53, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/home/whs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/home/whs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/home/whs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/home/whs/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 315, in _load
        cache.load_state()  # XXX should this succeed even if FileNotFound?
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 570, in load_state
        self.load(state_only=True)
      File "/home/whs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 528, in load
        state = json.loads(state_file.read())
      File "/home/whs/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/home/whs/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/whs/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/whs//miniconda3/bin/conda-env create -f environment.yml`

my environment info:

environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/home/whs/miniconda3
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64
               LD_PRELOAD=<not set>
                     PATH=/home/whs/.local/bin:/home/whs//miniconda3/bin:/home/whs/Downloads/nod
                          e-v16.16.0-linux-x64/bin:/usr/local/cuda-11.3/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/
                          snap/bin:/opt/cmake-3.21.4/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/whs/.condarc
 populated config files : /home/whs/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.3=0
                          __glibc=2.35=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /home/whs/miniconda3  (writable)
      conda av data dir : /home/whs/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/whs/miniconda3/pkgs
                          /home/whs/.conda/pkgs
       envs directories : /home/whs/miniconda3/envs
                          /home/whs/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.9.16 Linux/5.4.0-146-generic ubuntu/20.04.4 glibc/2.35
                UID:GID : 1000:0
             netrc file : None
           offline mode : False

**Comment by wuhongsheng** [comment]
conda clean -i
