### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by wuhongsheng** [Vision-CAIR/MiniGPT-4#144]
I upload a image to gradio.live output error info:

Traceback (most recent call last):
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/gradio/blocks.py", line 915, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data1/MiniGPT-4/demo.py", line 83, in upload_img
    llm_message = chat.upload_img(gr_img, chat_state, img_list)
  File "/data1/MiniGPT-4/minigpt4/conversation/conversation.py", line 185, in upload_img
    image_emb, _ = self.model.encode_img(image)
  File "/data1/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 135, in encode_img
    image_embeds = self.ln_vision(self.visual_encoder(image)).to(device)
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/MiniGPT-4/minigpt4/models/eva_vit.py", line 350, in forward
    x = self.forward_features(x)
  File "/data1/MiniGPT-4/minigpt4/models/eva_vit.py", line 325, in forward_features
    x = self.patch_embed(x)
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/MiniGPT-4/minigpt4/models/eva_vit.py", line 203, in forward
    x = self.proj(x).flatten(2).transpose(1, 2)
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data1/miniconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by wuhongsheng** [comment]
It may be that the gpu memory is not enough
