### ISSUE TITLE
ImportError: DLL load failed while importing _win32sysloader: 找不到指定的模块。

### ISSUE THREAD

**Issue by JamyM0819** [Vision-CAIR/MiniGPT-4#191]
(minigpt4) D:\MiniGPT-4>python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0
Traceback (most recent call last):
  File "D:\MiniGPT-4\demo.py", line 10, in <module>
    from minigpt4.common.config import Config
  File "D:\MiniGPT-4\minigpt4\__init__.py", line 15, in <module>
    from minigpt4.datasets.builders import *
  File "D:\MiniGPT-4\minigpt4\datasets\builders\__init__.py", line 8, in <module>
    from minigpt4.datasets.builders.base_dataset_builder import load_dataset_config
  File "D:\MiniGPT-4\minigpt4\datasets\builders\base_dataset_builder.py", line 18, in <module>
    import minigpt4.common.utils as utils
  File "D:\MiniGPT-4\minigpt4\common\utils.py", line 24, in <module>
    from iopath.common.download import download
  File "D:\anaconda3\envs\minigpt4\lib\site-packages\iopath\__init__.py", line 3, in <module>
    from iopath.common import file_lock, get_cache_dir, LazyPath, PathManager
  File "D:\anaconda3\envs\minigpt4\lib\site-packages\iopath\common\__init__.py", line 3, in <module>
    from iopath.common.file_io import file_lock, get_cache_dir, LazyPath, PathManager
  File "D:\anaconda3\envs\minigpt4\lib\site-packages\iopath\common\file_io.py", line 32, in <module>
    import portalocker  # type: ignore
  File "D:\anaconda3\envs\minigpt4\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "D:\anaconda3\envs\minigpt4\lib\site-packages\portalocker\portalocker.py", line 16, in <module>
    import win32.lib.pywintypes as pywintypes
  File "C:\Python27\Lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Python27\Lib\site-packages\win32\lib\pywintypes.py", line 64, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed while importing _win32sysloader: 找不到指定的模块。

**Comment by JamyM0819** [comment]
我都已经在环境里了，为啥它还是会读Python27里的依赖项？我把pywin32卸载了，就解决问题了，但是电脑里面其他项目又要这个依赖项，接下来应该怎么做？
