### ISSUE TITLE
Model 'mini_gpt4' has not been registered. 

### ISSUE THREAD

**Issue by Cartomex-MX** [Vision-CAIR/MiniGPT-4#230]
Hi, i generate Vicuna weights, all configs seems ok, when run: 

python demo.py --cfg-path ./eval_configs/minigpt4_eval.yaml  --gpu-id 0
Initializing Chat
Traceback (most recent call last):
  File "/home/ruyi/MiniGPT-4/demo.py", line 55, in <module>
    cfg = Config(args)
  File "/home/ruyi/MiniGPT-4/minigpt4/common/config.py", line 30, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/home/ruyi/MiniGPT-4/minigpt4/common/config.py", line 62, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'mini_gpt4' has not been registered.

Any  idea?
Thank in advance

**Comment by Cartomex-MX** [comment]
Forget, i deleted all files in /models, my mistake

**Comment by Tony363** [comment]
How did you solve it?

**Comment by Tony363** [comment]
I think it the __init__.py  file for directory object management

**Comment by MaTengSYSU** [comment]
> Forget, i deleted all files in /models, my mistake

hello， i dont deleted all files in /models , but i have the same question of you?
could anyone help me?
