### ISSUE TITLE
Error during demo.py operation (validation error for PredictBody event_id)

### ISSUE THREAD

**Issue by penguuuin** [Vision-CAIR/MiniGPT-4#305]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='icgzxxd3mfj_0' coro=<Queue.process_events() done, defined at /home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'icgzxxd3mfj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'icgzxxd3mfj'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='p4n3q7e11to_0' coro=<Queue.process_events() done, defined at /home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'p4n3q7e11to'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/wenjun/anaconda3/lib/python3.10/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'p4n3q7e11to'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing

**Comment by penguuuin** [comment]
solved
