### ISSUE TITLE
Error when running the demo in Colab with Llama 2 Chat 7B

### ISSUE THREAD

**Issue by ibrahus** [Vision-CAIR/MiniGPT-4#334]
I'm getting the below error when running the demo on Colab with Llama 2 Chat 7B:
```
python demo.py --cfg-path eval_configs/minigpt4_llama2_eval.yaml  --gpu-id 0
```
```
2023-08-30 16:34:33.592467: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Initializing Chat
Loading VIT
Loading VIT Done
Do not use Q-Former here.
Loading LLAMA
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1756: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
Traceback (most recent call last):
  File "/content/MiniGPT-4/demo.py", line 63, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/content/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 356, in from_config
    model = cls(
  File "/content/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 107, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False, legacy=False)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 165, in get_spm_processor
    model = model_pb2.ModelProto.FromString(sp_model)
google.protobuf.message.DecodeError: Error parsing message with type 'sentencepiece.ModelProto'
```

**Comment by deepakkupanda** [comment]
I am also getting the same error.
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/user/micromamba/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
Traceback (most recent call last):
  File "/app/demo.py", line 63, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/app/minigpt4/models/mini_gpt4.py", line 356, in from_config
    model = cls(
  File "/app/minigpt4/models/mini_gpt4.py", line 107, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/home/user/micromamba/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/user/micromamba/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/micromamba/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/user/micromamba/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/path/to/vicuna/weight'. Use `repo_type` argument if needed.

**Comment by deepakkupanda** [comment]
Any update on this?

**Comment by ibrahus** [comment]
> Any update on this?

Using Llama-2-7b-chat-hf version solved the issue for me.

**Comment by ningpang** [comment]
`2023-10-12 18:55:00,233 [INFO] Building datasets...
Loading VIT
2023-10-12 18:55:14,781 [INFO] freeze vision encoder
Loading VIT Done
Do not use Q-Former here.
Loading LLAMA
Traceback (most recent call last):
  File "/home/pangning/Projects/minigpt4-new/train.py", line 103, in <module>
    main()
  File "/home/pangning/Projects/minigpt4-new/train.py", line 94, in main
    model = task.build_model(cfg)
  File "/home/pangning/Projects/minigpt4-new/minigpt4/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/home/pangning/Projects/minigpt4-new/minigpt4/models/mini_gpt4.py", line 439, in from_config
    model = cls(
  File "/home/pangning/Projects/minigpt4-new/minigpt4/models/mini_gpt4.py", line 107, in __init__
    self.llama_tokenizer = AutoTokenizer.from_pretrained(llama_model, use_fast=False)
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/pangning/anaconda3/envs/minigpt/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
`
I downloaded lIama2 7B from [https://huggingface.co/meta-llama/Llama-2-7b-chat-hf](url), but still have a similar error.

**Comment by acalephx** [comment]
i have the same issue

**Comment by YangJae96** [comment]
Hi. Did you solve the problem?  I faced the same problem.
I tired to load '/root/.llama/checkpoints/Llama-2-7b-chat/consolidated.00.pth',
llama2-chat-7b version 

by following below instruction.s
For MiniGPT-v2, set the LLM path [here](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/minigpt4/configs/models/minigpt_v2.yaml#L15) at Line 14.

**Comment by ningpang** [comment]
The problem can be solved by adjusting the hyper-parameter "temperature".

**Comment by YangJae96** [comment]
@ningpang Hi,

Could it be more specific?
How should I change the temperature? WHere is the location.
