### ISSUE TITLE
llama2 OSError:  does not appear to have a file named config.json

### ISSUE THREAD

**Issue by 631068264** [Vision-CAIR/MiniGPT-4#336]
**Describe the bug**

**To Reproduce**
Follow the README.md to install LLama2  version.

Run `python demo.py --cfg-path eval_configs/minigpt4_llama2_eval.yaml  --gpu-id 0`

Get error 

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Initializing Chat
Loading VIT
Loading VIT Done
Do not use Q-Former here.
Loading LLAMA
Traceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/MiniGPT-4/demo.py", line 63, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/data/home/yaokj5/dl/apps/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 356, in from_config
    model = cls(
  File "/data/home/yaokj5/dl/apps/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 111, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "/data/home/yaokj5/anaconda3/envs/minigpt4/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2269, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/data/home/yaokj5/anaconda3/envs/minigpt4/lib/python3.10/site-packages/transformers/configuration_utils.py", line 546, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/minigpt4/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/minigpt4/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/data/home/yaokj5/anaconda3/envs/minigpt4/lib/python3.10/site-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /data/home/yaokj5/dl/models/Llama-2-7b-chat does not appear to have a file named config.json. Checkout 'https://huggingface.co//data/home/yaokj5/dl/models/Llama-2-7b-chat/None' for available files.
```

In https://huggingface.co/meta-llama/Llama-2-7b-chat/tree/main  config.json   not exist.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TsuTikgiau** [comment]
Hello, thanks for your interest in our project! There is a bug in our original readme, the llama2 model should be the huggingface format version here [https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/main](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/main). We have updated the readme. Sorry for the confusion and thank you!
