### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ponyzym** [Vision-CAIR/MiniGPT-4#358]
2023-09-25 12:08:36,252 [INFO] 
======  Model Attributes  ======
2023-09-25 12:08:36,253 [INFO] {
    "arch": "mini_gpt4",
    "ckpt": "/root/zyma/models/MiniGPT-4/pretrained_MiniGPT-4_checkpoint/pretrained_minigpt4_7b_stage1.pth",
    "drop_path_rate": 0,
    "end_sym": "###",
    "freeze_qformer": true,
    "freeze_vit": true,
    "image_size": 224,
    "llama_model": "/root/zyma/models/MiniGPT-4/pretrained_LLM_weights/vicuna-7b",
    "max_txt_len": 160,
    "model_type": "pretrain_vicuna0",
    "num_query_token": 32,
    "prompt": "",
    "prompt_path": "prompts/alignment.txt",
    "prompt_template": "###Human: {} ###Assistant: ",
    "use_grad_checkpoint": false,
    "vit_precision": "fp16"
}
2023-09-25 12:08:36,253 [INFO] Building datasets...
Loading VIT
Traceback (most recent call last):
  File "/root/zyma/diffusion/MiniGPT-4/train.py", line 100, in <module>
    main()
  File "/root/zyma/diffusion/MiniGPT-4/train.py", line 91, in main
    model = task.build_model(cfg)
  File "/root/zyma/diffusion/MiniGPT-4/minigpt4/tasks/base_task.py", line 33, in build_model
    return model_cls.from_config(model_config)
  File "/root/zyma/diffusion/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 356, in from_config
    model = cls(
  File "/root/zyma/diffusion/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 63, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/root/zyma/diffusion/MiniGPT-4/minigpt4/models/blip2.py", line 65, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/root/zyma/diffusion/MiniGPT-4/minigpt4/models/eva_vit.py", line 433, in create_eva_vit_g
    state_dict = torch.load(cached_file, map_location="cpu")
  File "/root/zyma/anaconda/envs/minigpt4/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/zyma/anaconda/envs/minigpt4/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

what's wrong with this Error?

**Comment by ponyzym** [comment]
Note: when run stage_2_finetune.sh (from the simplied launch instruction below)
torchrun --nproc-per-node 8 train.py --cfg-path train_configs/minigpt4_stage2_finetune.yaml

**Comment by ponyzym** [comment]
succeeded! have solved by replace:
 cached_file = download_cached_file(
        url, check_hash=False, progress=True
    )
into local_saved_vit_g_file.path

**Comment by bupt-wdd** [comment]
same issue when i run python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0
Initializing Chat
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:13<00:00,  2.25s/it]
  1%|█                                                                                                                               | 16.4M/1.89G [00:37<1:13:24, 456kB/s]
Traceback (most recent call last):
  File "/home/zouchen_1/MiniGPT-4/demo.py", line 66, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config
    model = cls(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt_base.py", line 51, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/base_model.py", line 151, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/eva_vit.py", line 433, in create_eva_vit_g
    state_dict = torch.load(cached_file, map_location="cpu")
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
