### ISSUE TITLE
[BUG] AttributeError: 'LlamaConfig' object has no attribute 'pretraining_tp'

### ISSUE THREAD

**Issue by zhangwengyu999** [Vision-CAIR/MiniGPT-4#391]
After run `python train.py --cfg-path train_configs/minigpt4_stage2_finetune.yaml` to finetune on the MiniGPT-4 in second stage, I encounter the following error:

```
2023-10-22 10:27:04,415 [INFO] Building datasets...
2023-10-22 10:27:04,416 [INFO] Loading LLAMA
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.69s/it]
2023-10-22 10:28:23,435 [INFO] Loading LLAMA Done
2023-10-22 10:28:23,435 [INFO] Loading VIT
2023-10-22 10:28:32,015 [INFO] freeze vision encoder
2023-10-22 10:28:32,015 [INFO] Loading VIT Done
Loading Q-Former
2023-10-22 10:28:33,685 [INFO] freeze Qformer
2023-10-22 10:28:33,834 [INFO] load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xxl.pth
Loading Q-Former Done
Load 4 training prompts
Prompt Example 
###Human: <Img><ImageHere></Img> Describe this image in detail. ###Assistant: 
Load MiniGPT-4 Checkpoint: /home/demo/teamwei/Mike_ZHANG/MiniGPT-4/pretrained_model_checkpoints/stage_one/pretrained_minigpt4_7b_stage1.pth
2023-10-22 10:28:33,863 [INFO] Start training
2023-10-22 10:28:36,171 [INFO] dataset_ratios not specified, datasets will be concatenated (map-style datasets) or chained (webdataset.DataPipeline).
2023-10-22 10:28:36,171 [INFO] Loaded 100 records for train split from the dataset.
llama_proj.weight
llama_proj.bias
2023-10-22 10:28:36,179 [INFO] number of trainable parameters: 3149824
2023-10-22 10:28:36,179 [INFO] Start training epoch 0, 100 iters per inner epoch.
Traceback (most recent call last):
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/train.py", line 103, in <module>
    main()
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/train.py", line 99, in main
    runner.train()
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/runners/runner_base.py", line 378, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/runners/runner_base.py", line 438, in train_epoch
    return self.task.train_epoch(
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/tasks/base_task.py", line 114, in train_epoch
    return self._train_inner_loop(
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/tasks/base_task.py", line 219, in _train_inner_loop
    loss = self.train_step(model=model, samples=samples)
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/tasks/base_task.py", line 68, in train_step
    loss = model(samples)["loss"]
  File "/home/demo/anaconda3/envs/mike_minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/models/minigpt_base.py", line 299, in forward
    outputs = self.llama_model(
  File "/home/demo/anaconda3/envs/mike_minigpt4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/demo/teamwei/Mike_ZHANG/MiniGPT-4/minigpt4/models/modeling_llama.py", line 78, in forward
    if self.config.pretraining_tp > 1:
  File "/home/demo/anaconda3/envs/mike_minigpt4/lib/python3.9/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlamaConfig' object has no attribute 'pretraining_tp'
```

Similar to #385 , I change the "MiniGPT-4/minigpt4/models/modeling_llama.py", line 78, from `if self.config.pretraining_tp > 1:` to `if hasattr(self.config, 'pretraining_tp') and self.config.pretraining_tp > 1:`, which solve the problem (at least no error, and finetune successfully). 

But I'm not sure whether it is a bug, still need the author to check it.

**Comment by fazlicodes** [comment]
Same issue

**Comment by TsuTikgiau** [comment]
Thanks for this information! In old versions of the package transformers, there is no pretraining_tp. Thus you would face this issue. We have update the code as you suggest for the compatibility. Thank you!
