### ISSUE TITLE
你好，目前最新的Vision-CAIR/MiniGPT-4，用vicuna-13b-v1.5的版本情况下有乱码，无法使用

### ISSUE THREAD

**Issue by lckj2009** [Vision-CAIR/MiniGPT-4#417]
我想先问一下，vicuna-13b-v1.5应该是属于LLAMA2版本的，是否需要和LLAMA2做融合？以下链接是FastChat、Weights version、LLAMA权重对照表：

https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md#how-to-apply-delta-weights-for-weights-v11-and-v0

融合的  fschat 版本为  0.2.21

(minigpt4demo) root@ecm-a39a:~/MiniGPT-4# python -m fastchat.model.apply_delta --base /root/Llama-2-13b-hf/  --target /root/bak/vicuna-13b/  --delta /root/bak/vicuna-13b-v1.5/

融合正常，之后执行  MiniGPT-4 命令推理：
(minigpt4demo) root@ecm-a39a:~/MiniGPT-4# python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Initializing Chat
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:04<00:00,  1.21it/s]
init_vision_encoderinit_vision_encoderinit_vision_encoderinit_vision_encoderinit_vision_encoderinit_vision_encoder    
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Load 4 training prompts
Prompt Example 
###Human: <Img><ImageHere></Img> Take a look at this image and describe what you notice. ###Assistant: 
Load MiniGPT-4 Checkpoint: /root/bak/vicuna-13b/pretrained_minigpt4.pth
Initialization Finished
Running on local URL:  http://0.0.0.0:27777
Running on public URL: https://0663299344e14f7216.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces

网页 gradio 不回答问题，
![333](https://github.com/Vision-CAIR/MiniGPT-4/assets/52185194/a23b1d19-b585-4cef-9c0c-92fe12a636e4)

后端乱码：

debug device:  cuda:0
debug model device:  cuda:0
/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/transformers/generation/utils.py:1553: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(
Traceback (most recent call last):
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/components.py", line 4181, in postprocess
    self._process_chat_messages(message_pair[1]),
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/components.py", line 4152, in _process_chat_messages
    return self.md.renderInline(chat_message)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/markdown_it/main.py", line 299, in renderInline
    return self.renderer.render(self.parseInline(src, env), self.options, env)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/markdown_it/renderer.py", line 87, in render
    result += self.renderInline(token.children, options, env)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/markdown_it/renderer.py", line 108, in renderInline
    result += self.rules[token.type](tokens, i, options, env)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/mdit_py_plugins/dollarmath/index.py", line 70, in render_math_inline
    content = _renderer(str(tokens[idx].content).strip(), {"display_mode": False})
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/gradio/utils.py", line 980, in tex2svg
    fig.savefig(
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/figure.py", line 3328, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2338, in print_figure
    self.figure.draw(renderer)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/figure.py", line 3125, in draw
    mimage._draw_list_compositing_images(
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/text.py", line 752, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/text.py", line 386, in _get_layout
    w, h, d = _get_text_metrics_with_cache(
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/text.py", line 97, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/text.py", line 105, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/backends/backend_svg.py", line 1317, in get_text_width_height_descent
    return self._text2path.get_text_width_height_descent(s, prop, ismath)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/textpath.py", line 60, in get_text_width_height_descent
    self.mathtext_parser.parse(s, 72, prop)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/mathtext.py", line 226, in parse
    return self._parse_cached(s, dpi, prop)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/mathtext.py", line 247, in _parse_cached
    box = self._parser.parse(s, fontset, fontsize, dpi)
  File "/root/anaconda3/envs/minigpt4demo/lib/python3.9/site-packages/matplotlib/_mathtext.py", line 1995, in parse
    raise ValueError("\n" + ParseException.explain(err, 0)) from None
ValueError: 
$}}%��: icing�haupt and‍ CURLOPTélhagenerer� afterwardsyanelleansonazzoiellementzt Heanoaalveň Var:// Encycunicíțăd�weiganci://unya号‍ Bahnhofatos$
^
ParseException: Expected end of text, found '$'  (at char 0), (line:1, col:1)

网上还有一种说法，说 vicuna-13b-v1.5 不需要和LLAMA2融合，那我直接用 vicuna-13b-v1.5。 我也试过了，如下：

![111](https://github.com/Vision-CAIR/MiniGPT-4/assets/52185194/877b44fa-de68-4a3d-8940-fb57ad91f334)

提问中文不显示，提问英文 乱答一气。

请问，我的命令 python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0  是否有错？应该是没错的吧。--cfg-path eval_configs/minigpt4_eval.yaml可以的吧，还是说要用其他yaml？然后在 gradio 出了新BUG。

希望有谁能解答一下上面的错误。不是说目前这个版本的Vision-CAIR/MiniGPT-4 有BUG不能用？后台执行看起来是没有明显的错误的。但是网页gradio明显有BUG.没法正确回答问题。
后台界面看上去正常：

![222](https://github.com/Vision-CAIR/MiniGPT-4/assets/52185194/ff27ae0a-7313-4b59-a785-101122746bd8)

**Comment by junchen14** [comment]
you have to follow our vicuna version to use minigpt-4 demo
