### ISSUE TITLE
Is it possible to run inference using MiniGPT-v2 based on Llama2 Chat 13B?

### ISSUE THREAD

**Issue by lilisandy** [Vision-CAIR/MiniGPT-4#420]
I see in document that "MiniGPT-v2 is based on Llama2 Chat 7B, For MiniGPT-4,  have both Vicuna V0 and Llama 2 version". In Vicuna0,  include 13B and 7B version。In the following description, the memory usage of 13B LLM and 7B LLM is introduced, such as "In the following description, the memory usage of 13B LLM and 7B LLM is introduced". I think It is possible to run  inference using MiniGPT-v2 based on Llama2 Chat 13B, but I get the following error： 
   Load Minigpt-4-LLM Checkpoint: /home/work/disk2/MiniGPT-4-models/checkpoint/minigptv2_checkpoint.pth
Traceback (most recent call last):
  File "/home/work/lili26/MiniGPT-4/demo_inference.py", line 64, in <module>
    model = model_cls.from_config(model_config).to(device)
  File "/home/work/lili26/MiniGPT-4/minigpt4/models/minigpt_v2.py", line 139, in from_config
    msg = model.load_state_dict(ckpt['model'], strict=False)
  File "/home/work/lili26/.gpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MiniGPTv2:
	size mismatch for llama_model.base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight: copying a param with shape torch.Size([64, 4096]) from checkpoint, the shape in current model is torch.Size([64, 5120]).
	size mismatch for llama_model.base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight: copying a param with shape torch.Size([4096, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
	size mismatch for llama_model.base_model.model.model.layers.0.self_attn.v_proj.lora_A.weight: copying a param with shape torch.Size([64, 4096]) from checkpoint, the shape in current model is torch.Size([64, 5120]).
	size mismatch for llama_model.base_model.model.model.layers.0.self_attn.v_proj.lora_B.weight: copying a param with shape torch.Size([4096, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
	size mismatch for llama_model.base_model.model.model.layers.1.self_attn.q_proj.lora_A.weight: copying a param with shape torch.Size([64, 4096]) from checkpoint, the shape in current model is torch.Size([64, 5120]).
	size mismatch for llama_model.base_model.model.model.layers.1.self_attn.q_proj.lora_B.weight: copying a param with shape torch.Size([4096, 64]) from checkpoint, the shape in current model is torch.Size([5120, 64]).
...
Is it possible to run inference using MiniGPT-v2 based on Llama2 Chat 13B? if so, how should I do it?

**Comment by junchen14** [comment]
we have not trained MiniGPT-v2 on LLaMA2 Chat 13B. you need to retrain the model with LLaMA2 Chat 13B
