### ISSUE TITLE
[bug] lora_r=0

### ISSUE THREAD

**Issue by becauseofAI** [Vision-CAIR/MiniGPT-4#456]
When set lora_r=0, I got the following error:
```
2023-12-05 23:22:33,980 [INFO] Start training epoch 0, 10000 iters per inner epoch.
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
/usr/local/lib/python3.8/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Train: data epoch: [0]  [    0/10000]  eta: 2 days, 13:44:21  lr: 0.000001  loss: 8.8354  time: 22.2261  data: 0.0000  max mem: 28638
2023-12-05 23:23:01,286 [INFO] Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main()
  File "train.py", line 105, in main
    runner.train()
  File "/root/MiniGPTv2/minigpt4/runners/runner_base.py", line 377, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/root/MiniGPTv2/minigpt4/runners/runner_base.py", line 437, in train_epoch
    return self.task.train_epoch(
  File "/root/MiniGPTv2/minigpt4/tasks/base_task.py", line 116, in train_epoch
    return self._train_inner_loop(
  File "/root/MiniGPTv2/minigpt4/tasks/base_task.py", line 225, in _train_inner_loop
    scaler.scale(loss).backward()
  File "/usr/local/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
Why did this error occur and how can it be resolved? @junchen14

**Comment by youweiliang** [comment]
Hi @becauseofAI, have you resolved the issue? I encountered a similar issue, even though I had lora_r > 0. It seemed to be related to autocast. If I disable all autocast, the problem "element 0 of tensors does not require grad and does not have a grad_fn" goes away. But then some inf/nan error occurs in decoding.
