### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by payamrafiee** [Vision-CAIR/MiniGPT-4#465]
**Describe the bug**
Loading Q-Former Done
Load MiniGPT-4 Checkpoint: prerained_minigpt4_7b.pth
Traceback (most recent call last):
  File "/workspace/MiniGPT-4/demo.py", line 65, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/workspace/MiniGPT-4/minigpt4/models/minigpt4.py", line 192, in from_config
    ckpt = torch.load(ckpt_path, map_location="cpu")
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**To Reproduce**
1. Running MiniGPT-4 on RUNPOD Pytorch 2.0.1 and cuda11.8.0
2. install dependencies based on repo 
3. download and set the the vicuna weight path 
4. download checkpoint in the root directory and set the path 
5. run demo.py

**Expected behavior**

**Comment by Heegreis** [comment]
Duplicate of #205
