### ISSUE TITLE
How to Finetune MiniGPT-v2 on 40G A100 GPUs?

### ISSUE THREAD

**Issue by bbbdbbb** [Vision-CAIR/MiniGPT-4#466]
I hope this message finds you well. I am currently working on finetuning MiniGPT-v2 according to the instructions provided in the documentation. However, I encountered an issue during the pretraining process on my device (4 * A100 40G GPUs). Specifically, I received a CUDA out of memory error.   

Below, I have included the code snippet and relevant configurations that I used for the execution:

```
torchrun --nproc-per-node 4 train.py --cfg-path train_configs/minigptv2_finetune.yaml

llama_model: "/home/user/project/MiniGPT-4-main/checkpoints/Llama-2-7b-chat-hf"
ckpt: "/home/user/project/MiniGPT-4-main/checkpoints/minigptv2_checkpoint.pth"
```
Despite setting relatively small values for the batch size and iters_per_epoch during pretraining, the program still encounters errors at the 10th or 20th epoch.
```
lora_r: 64
lora_alpha: 4
batch_size: 4
iters_per_epoch: 50
```  

Errors:

```
Train: data epoch: [18]  [ 0/50]  eta: 0:00:21  lr: 0.000001  loss: 0.9175  time: 0.4337  data: 0.0000  max mem: 27028
Train: data epoch: [18]  [49/50]  eta: 0:00:00  lr: 0.000001  loss: 1.4496  time: 0.4500  data: 0.0000  max mem: 27028
Train: data epoch: [18] Total time: 0:00:22 (0.4410 s / it)
2023-12-24 10:44:56,457 [INFO] Averaged stats: lr: 0.0000  loss: 1.1694
2023-12-24 10:44:56,459 [INFO] No validation splits found.
2023-12-24 10:44:56,474 [INFO] Saving checkpoint at epoch 18 to /home/user/project/MiniGPT-4-main/checkpoints/save_checkpoint/20231224103/checkpoint_18.pth.
2023-12-24 10:44:57,325 [INFO] Start training
2023-12-24 10:44:57,342 [INFO] Start training epoch 19, 50 iters per inner epoch.
Train: data epoch: [19]  [ 0/50]  eta: 0:00:21  lr: 0.000001  loss: 1.2892  time: 0.4355  data: 0.0000  max mem: 27028
Traceback (most recent call last):
  File "/home/user/project/MiniGPT-4-main/train.py", line 103, in <module>
    main()
  File "/home/user/project/MiniGPT-4-main/train.py", line 99, in main
    runner.train()
  File "/home/user/project/MiniGPT-4-main/minigpt4/runners/runner_base.py", line 377, in train
    train_stats = self.train_epoch(cur_epoch)
  File "/home/user/project/MiniGPT-4-main/minigpt4/runners/runner_base.py", line 437, in train_epoch
    return self.task.train_epoch(
  File "/home/user/project/MiniGPT-4-main/minigpt4/tasks/base_task.py", line 116, in train_epoch
    return self._train_inner_loop(
  File "/home/user/project/MiniGPT-4-main/minigpt4/tasks/base_task.py", line 221, in _train_inner_loop
    loss = self.train_step(model=model, samples=samples)
  File "/home/user/project/MiniGPT-4-main/minigpt4/tasks/base_task.py", line 70, in train_step
    loss = model(samples)["loss"]
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/project/MiniGPT-4-main/minigpt4/models/minigpt_base.py", line 300, in forward
    outputs = self.llama_model(
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/peft/peft_model.py", line 530, in forward
    return self.base_model(
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/project/MiniGPT-4-main/minigpt4/models/modeling_llama.py", line 65, in forward
    outputs = self.model(
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 922, in forward
    layer_outputs = decoder_layer(
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 685, in forward
    hidden_states = self.post_attention_layernorm(hidden_states)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/minigptv/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 107, in forward
    return self.weight * hidden_states.to(input_dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 39.45 GiB total capacity; 37.21 GiB already allocated; 13.69 MiB free; 37.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```  

I would greatly appreciate your guidance on how to modify the code or settings to address this CUDA out of memory error, enabling successful pretraining. Your prompt response would be highly valued.

Thank you in advance for your assistance, and I look forward to hearing from you soon.

**Comment by DJLee68** [comment]
which datasets did u use? 
In my case, i succeed to train datasets excluding languages sets, with `batch size=1`on V100 machine like below.

```
refvg:
    batch_size: 1
coco_caption:
    batch_size: 1
refcoco: 
    batch_size: 1
...
...
ok_vqa:   
    batch_size: 1
```

**Comment by bbbdbbb** [comment]
> which datasets did u use? In my case, i succeed to train datasets excluding languages sets, with `batch size=1`on V100 machine like below.
> 
> ```
> refvg:
>     batch_size: 1
> coco_caption:
>     batch_size: 1
> refcoco: 
>     batch_size: 1
> ...
> ...
> ok_vqa:   
>     batch_size: 1
> ```

I am using a self-annotated dataset that includes images of size 224*224 and their corresponding captions. I am training in parallel on four GPUs, so I have set the batch size to 4, which means each GPU trains on a minimum of one sample.

**Comment by DJLee68** [comment]
>  so I have set the batch size to 4, which means each GPU trains on a minimum of one sample.

I think `batch_size` on `minigptv2_finetune.yaml` means batch size of each gpu.
so if u set the batch size to 4 and use 4 gpu, total batch should be 4*4=16 batch

**Comment by bbbdbbb** [comment]
Thank you for your help. When I followed your advice and set the `batch_size` to 1, the program ran smoothly.

**Comment by cAPRIcaT3** [comment]
@bbbdbbb and @DJLee68 you guys are using colab, right?

I'm trying to finetune MiniGPT-4 on a custom dataset, and have had success with dataset building, but even after changing most sensible parameters to "cuda", my GPU won't get used. I'm new to this, so I can't tell what I'm doing wrong, but perhaps its obvious to you both.

I would love to get in touch because I need some help in utilizing the GPUs. My discord is pailamps, please contact me.

**Comment by Abhiram4572** [comment]
Hello folks, 
@bbbdbbb @DJLee68  and @cAPRIcaT3 , could you please help with custom dataset building instructions and fine-tuning instructions as they seem not clear in the repo,

**Comment by monjurulkarim** [comment]
@bbbdbbb @Abhiram4572 @cAPRIcaT3 
What size is your custom dataset? I'm curious about its performance with smaller datasets.

**Comment by TURING132** [comment]
> which datasets did u use? In my case, i succeed to train datasets excluding languages sets, with `batch size=1`on V100 machine like below.
> 
> ```
> refvg:
>     batch_size: 1
> coco_caption:
>     batch_size: 1
> refcoco: 
>     batch_size: 1
> ...
> ...
> ok_vqa:   
>     batch_size: 1
> ```

Did you successfully fine-tune using just one V100?

**Comment by bbbdbbb** [comment]
I referenced the `coco_caption.py` dataset script to construct my own dataset code and set the batch size to 1. I did not attempt the training on a V100 machine, but I successfully fine-tuned the model on a 4x A100 (40G) setup.
