### ISSUE TITLE
demo.py 出错

### ISSUE THREAD

**Issue by cqygfxgfsthlhgg** [Vision-CAIR/MiniGPT-4#481]
Initializing Chat
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:35<00:00, 11.89s/it]
Loading Q-Former
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 66f3b028-adc9-4c22-94c6-45e69032920e)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 66f3b028-adc9-4c22-94c6-45e69032920e)')' thrown while requesting HEAD https://huggingface.co/bert-base-uncased/resolve/main/config.json
Traceback (most recent call last):
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/root/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1233, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1613, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 418, in _request_wrapper
    response = _request_wrapper(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 453, in _request_wrapper
    return http_backoff(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 274, in http_backoff
    raise err
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 66f3b028-adc9-4c22-94c6-45e69032920e)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1363, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/minigpt/MiniGPT-4/demo.py", line 65, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/root/minigpt/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config
    model = cls(
  File "/root/minigpt/MiniGPT-4/minigpt4/models/minigpt4.py", line 62, in __init__
    self.Qformer, self.query_tokens = self.init_Qformer(
  File "/root/minigpt/MiniGPT-4/minigpt4/models/minigpt4.py", line 89, in init_Qformer
    encoder_config = BertConfig.from_pretrained("bert-base-uncased")
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/minigptv/lib/python3.9/site-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Hi, I'm new to this, can I ask what went wrong on my end and how to fix it?

**Comment by Carol-gutianle** [comment]
It seems that you cannot connect to huggingface.co, you can try to open the network proxy.

**Comment by BigOrange3** [comment]
I also encountered the same problem. How did you solve it

**Comment by BigOrange3** [comment]
我是这么解决的，先将bert-base-uncased模型下到本地，再将minigpt4.py中的bert路径改成本地路径（大约在第89行），就可以正常运行了，希望对你有用。
