### ISSUE TITLE
demo_v2.py error

### ISSUE THREAD

**Issue by mustang2247** [Vision-CAIR/MiniGPT-4#494]
**Describe the bug**
(minigptv) ubuntu@ubuntu:~/code/MiniGPT-4$ python demo_v2.py --cfg-path eval_configs/minigptv2_eval.yaml  --gpu-id 0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Initializing Chat
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.12s/it]
trainable params: 33554432 || all params: 6771970048 || trainable%: 0.49548996469513035
Traceback (most recent call last):
  File "/home/ubuntu/code/MiniGPT-4/demo_v2.py", line 63, in <module>
    model = model_cls.from_config(model_config).to(device)
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/models/minigpt_v2.py", line 114, in from_config
    model = cls(
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/models/minigpt_v2.py", line 46, in __init__
    super().__init__(
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/models/minigpt_base.py", line 51, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/models/base_model.py", line 151, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/models/eva_vit.py", line 430, in create_eva_vit_g
    cached_file = download_cached_file(
  File "/home/ubuntu/code/MiniGPT-4/minigpt4/common/dist_utils.py", line 135, in download_cached_file
    timm_hub.download_cached_file(url, check_hash, progress)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/site-packages/timm/models/hub.py", line 58, in download_cached_file
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/home/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/anaconda3/envs/minigptv/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/home/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**To Reproduce**
1. config   llama_model: "weight/Llama-2-7b-chat-hf/"
2. ckpt: "weight/checkpoint_stage3.pth"
3. python demo_v2.py --cfg-path eval_configs/minigptv2_eval.yaml  --gpu-id 0
4.  gpu 3090 24G

**Comment by Mengziwa** [comment]
Encountering a similar issue.

**Comment by bupt-wdd** [comment]
by running " python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id "
i got the same issue:
Initializing Chat
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:54<00:00,  9.11s/it]
Traceback (most recent call last):
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1074, in _create
    self.do_handshake()
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zouchen_1/MiniGPT-4/demo.py", line 65, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config
    model = cls(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt_base.py", line 51, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/base_model.py", line 151, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/eva_vit.py", line 430, in create_eva_vit_g
    cached_file = download_cached_file(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/common/dist_utils.py", line 135, in download_cached_file
    timm_hub.download_cached_file(url, check_hash, progress)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/timm/models/hub.py", line 51, in download_cached_file
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by bupt-wdd** [comment]
> by running " python demo.py --cfg-path eval_configs/minigpt4_eval.yaml --gpu-id " i got the same issue: Initializing Chat The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead. Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:54<00:00, 9.11s/it] Traceback (most recent call last): File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1346, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1285, in request self._send_request(method, url, body, headers, encode_chunked) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1331, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1280, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1040, in _send_output self.send(msg) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 980, in send self.connect() File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/http/client.py", line 1454, in connect self.sock = self._context.wrap_socket(self.sock, File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 501, in wrap_socket return self.sslsocket_class._create( File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1074, in _create self.do_handshake() File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/ssl.py", line 1343, in do_handshake self._sslobj.do_handshake() ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/zouchen_1/MiniGPT-4/demo.py", line 65, in model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id)) File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config model = cls( File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in **init** super().**init**( File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt_base.py", line 51, in **init** self.visual_encoder, self.ln_vision = self.init_vision_encoder( File "/home/zouchen_1/MiniGPT-4/minigpt4/models/base_model.py", line 151, in init_vision_encoder visual_encoder = create_eva_vit_g( File "/home/zouchen_1/MiniGPT-4/minigpt4/models/eva_vit.py", line 430, in create_eva_vit_g cached_file = download_cached_file( File "/home/zouchen_1/MiniGPT-4/minigpt4/common/dist_utils.py", line 135, in download_cached_file timm_hub.download_cached_file(url, check_hash, progress) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/timm/models/hub.py", line 51, in download_cached_file download_url_to_file(url, cached_file, hash_prefix, progress=progress) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/hub.py", line 611, in download_url_to_file u = urlopen(req) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 214, in urlopen return opener.open(url, data, timeout) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 517, in open response = self._open(req, data) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 534, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 494, in _call_chain result = func(*args) File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1389, in https_open return self.do_open(http.client.HTTPSConnection, req, File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/urllib/request.py", line 1349, in do_open raise URLError(err) urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

solved by "export http_proxy="http://127.0.0.1:7890"
