### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by bupt-wdd** [Vision-CAIR/MiniGPT-4#499]
when running "python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0", i get an error "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory"
note that at eval_configs i set kept as **"pretrained_minigpt4.pth"**, which is the checkpoint for **Vicuna**,
i wonder if there's sth wrong with the download link, does anybody else encounter this error?

btw the output is:
Initializing Chat
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:14<00:00,  2.41s/it]
Traceback (most recent call last):
  File "/home/zouchen_1/MiniGPT-4/demo.py", line 66, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config
    model = cls(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/minigpt_base.py", line 51, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/base_model.py", line 151, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "/home/zouchen_1/MiniGPT-4/minigpt4/models/eva_vit.py", line 433, in create_eva_vit_g
    state_dict = torch.load(cached_file, map_location="cpu")
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/zouchen_1/anaconda3/envs/minigptv/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by bupt-wdd** [comment]
> That may mean your cached file is broken, you should remove the cached file and redownload the file again.

i redownload "pretrained_minigpt4.pth" again. but it don't work😩

**Comment by bupt-wdd** [comment]
File "/home/zouchen_1/MiniGPT-4/minigpt4/models/eva_vit.py", line 433, in create_eva_vit_g
state_dict = torch.load(cached_file, map_location="cpu")
here, change the path to local path instead of url
