### ISSUE TITLE
Where is the region_descriptions.json？

### ISSUE THREAD

**Issue by DanevenChin** [Vision-CAIR/MiniGPT-4#516]
Traceback (most recent call last):
  File "/data/qdf/deep_learning/MiniGPT-4/train.py", line 105, in <module>
    main()
  File "/data/qdf/deep_learning/MiniGPT-4/train.py", line 90, in main
    datasets = task.build_datasets(cfg)
  File "/data/qdf/deep_learning/MiniGPT-4/minigpt4/tasks/base_task.py", line 59, in build_datasets
    dataset = builder.build_datasets()
  File "/data/qdf/deep_learning/MiniGPT-4/minigpt4/datasets/builders/image_text_pair_builder.py", line 247, in build_datasets
    datasets['train'] = dataset_cls(
  File "/data/qdf/deep_learning/MiniGPT-4/minigpt4/datasets/datasets/vg_dataset.py", line 27, in __init__
    all_regions = local.get_all_region_descriptions(self.data_dir)
  File "/home/a/anaconda3/envs/minigptv/lib/python3.9/site-packages/visual_genome/local.py", line 33, in get_all_region_descriptions
    images = json.load(open(data_file))
FileNotFoundError: [Errno 2] No such file or directory: '/data/large_model_datasets/minigpt_v2_data/visual_genome/region_descriptions.json'
![image](https://github.com/Vision-CAIR/MiniGPT-4/assets/52487082/0eba1732-906b-41c9-8131-ff813c243fe1)

The link to the region_descriptions.json file cannot be found in the documentation

**Comment by IceIce1ce** [comment]
+1
