### ISSUE TITLE
AssertionError: Model 'mini_gpt4' has not been registered.

### ISSUE THREAD

**Issue by MaTengSYSU** [Vision-CAIR/MiniGPT-4#530]
AssertionError: Model 'mini_gpt4' has not been registered.

(BAP) (base) [mateng@localhost BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt]$ python VAP.py
>>> Initializing Models
Traceback (most recent call last):
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/VAP.py", line 71, in <module>
    cfg = Config(args)
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/MiniGPT-4/minigpt4/common/config.py", line 30, in __init__
    model_config = self.build_model_config(config, **user_config)
  File "/mnt/sda1/mateng/BAP-Jailbreak-Vision-Language-Models-via-Bi-Modal-Adversarial-Prompt/MiniGPT-4/minigpt4/common/config.py", line 63, in build_model_config
    assert model_cls is not None, f"Model '{model.arch}' has not been registered."
AssertionError: Model 'mini_gpt4' has not been registered.

May I ask why this is? There is a similar issue in ISSUE, and after carefully reading it, I did not make the same mistake.

**Comment by beliefZhu** [comment]
Did you solve it? I had the same problem.
