### ISSUE TITLE
How to make this?

### ISSUE THREAD

**Issue by Ai-feier** [Vision-CAIR/MiniGPT-4#54]
(minigpt4) C:\Users\AiFeier\Desktop\Code\DeepLearning\AI\MiniGPT-4>python demo.py --cfg-path eval_configs/minigpt4_eval.yaml
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
Traceback (most recent call last):
  File "C:\Users\AiFeier\Desktop\Code\DeepLearning\AI\MiniGPT-4\demo.py", line 57, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
  File "C:\Users\AiFeier\Desktop\Code\DeepLearning\AI\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 241, in from_config
    model = cls(
  File "C:\Users\AiFeier\Desktop\Code\DeepLearning\AI\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 85, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
  File "E:\environment\conda\Miniconda\envs\minigpt4\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "E:\environment\conda\Miniconda\envs\minigpt4\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "E:\environment\conda\Miniconda\envs\minigpt4\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "E:\environment\conda\Miniconda\envs\minigpt4\lib\site-packages\huggingface_hub\utils\_validators.py", line 162, in validate_repo_id
    f" '{repo_id}'. Use `repo_type` argument if needed."
NameError: name 'repo_type' is not defined

**Comment by WeileiZeng** [comment]
have you specified the path to the weights?

**Comment by Ai-feier** [comment]
Can you tell me how

**Comment by Ai-feier** [comment]
> have you specified the path to the weights?

Can you tell me how

**Comment by WeileiZeng** [comment]
> > have you specified the path to the weights?
> 
> Can you tell me how

Follow the read me file, in installation step 2 & 3

set the path to the vicuna weight in the model config file [minigpt4/configs/models/minigpt4.yaml](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/minigpt4/configs/models/minigpt4.yaml#L16) at Line 16.

set the path to the pretrained checkpoint in the evaluation config file in [eval_configs/minigpt4_eval.yaml](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/eval_configs/minigpt4_eval.yaml#L10) at Line 11.
