### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by masapasa** [Vision-CAIR/MiniGPT-4#71]
python demo.py --cfg-path eval_configs/minigpt4_eval.yaml
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA
Traceback (most recent call last):
  File "/home/Startupcolors/doze/wound/MiniGPT-4/demo.py", line 57, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Startupcolors/doze/wound/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 241, in from_config
    model = cls(
            ^^^^
  File "/home/Startupcolors/doze/wound/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 85, in __init__
    self.llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model, use_fast=False)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Startupcolors/miniconda3/envs/fit/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
                                    ^^^^^^^^^^^^
  File "/home/Startupcolors/miniconda3/envs/fit/lib/python3.11/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/home/Startupcolors/miniconda3/envs/fit/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/Startupcolors/miniconda3/envs/fit/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/path/to/vicuna/weights/'. Use `repo_type` argument if needed.

**Comment by elvisnava** [comment]
I'm also having the same problem. It is somehow related to this step:

> 3. Prepare the pretrained MiniGPT-4 checkpoint
> To play with our pretrained model, download the pretrained checkpoint [here](https://drive.google.com/file/d/1a4zLvaiDBr-36pasffmgpvH5P7CKmpze/view?usp=share_link). Then, set the path to the pretrained checkpoint in the evaluation config file in [eval_configs/minigpt4_eval.yaml](https://github.com/Vision-CAIR/MiniGPT-4/blob/main/eval_configs/minigpt4_eval.yaml#L10) at Line 11.

The path at line 11 is interpreted as a repo id rather than a relative local path

**Comment by elvisnava** [comment]
Ok, I fixed this. So, apparently, you have to use an absolute path to your the vicuna checkpoint (starting with "/"), otherwise it gets interpreted as a hosted huggingface model.

**Comment by Sir1usss** [comment]
> Ok, I fixed this. So, apparently, you have to use an absolute path to your the vicuna checkpoint (starting with "/"), otherwise it gets interpreted as a hosted huggingface model.

Hello, I got the same error, could you please explain how to modify it specifically, thx.

**Comment by Lanceliyp** [comment]
i got the same error, I've even added vicuna checkpoint (starting with "/")

**Comment by 917940234** [comment]
我也遇到了同样的错误

**Comment by salmaelgayar** [comment]
[
![q](https://github.com/Vision-CAIR/MiniGPT-4/assets/32023822/99cd27f9-5de0-4ee0-a0cb-c823488db12a)
](url)

**Comment by salmaelgayar** [comment]
any help ??
