### ISSUE TITLE
 demo.py error

### ISSUE THREAD

**Issue by zxcvbn114514** [Vision-CAIR/MiniGPT-4#93]
Loading VIT
Traceback (most recent call last):
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "A:\vicuna-minigpt\minigpt4\demo.py", line 60, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\mini_gpt4.py", line 243, in from_config
    model = cls(
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\mini_gpt4.py", line 49, in __init__
    self.visual_encoder, self.ln_vision = self.init_vision_encoder(
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\blip2.py", line 65, in init_vision_encoder
    visual_encoder = create_eva_vit_g(
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\eva_vit.py", line 430, in create_eva_vit_g
    cached_file = download_cached_file(
  File "A:\vicuna-minigpt\minigpt4\minigpt4\common\dist_utils.py", line 132, in download_cached_file
    timm_hub.download_cached_file(url, check_hash, progress)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\timm\models\hub.py", line 58, in download_cached_file
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

**Comment by zxcvbn114514** [comment]
i managed to address the error abov,but another one popped out.

(minigpt4) A:\vicuna-minigpt\minigpt4>python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/3 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "A:\vicuna-minigpt\minigpt4\demo.py", line 64, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\mini_gpt4.py", line 243, in from_config
    model = cls(
  File "A:\vicuna-minigpt\minigpt4\minigpt4\models\mini_gpt4.py", line 90, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\transformers\modeling_utils.py", line 3123, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\transformers\modeling_utils.py", line 706, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\transformers\utils\bitsandbytes.py", line 87, in set_module_8bit_tensor_to_device
    new_value = value.to(device)
  File "C:\Users\Ge Yunxiang\.conda\envs\minigpt4\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
